### PR TITLE
keyboard_indicators: fix segfault when -s is specified

### PR DESCRIPTION
**Pull request by R41z**
tl;dr

```
[raiz@localhost slstatus]$ make
cc -o slstatus -std=c99 -pedantic -Wall -Wextra -Wno-unused -Os -I/usr/X11R6/include -D_DEFAULT_SOURCE -L/usr/X11R6/lib -s slstatus.c -lX11
[raiz@localhost slstatus]$ ./slstatus -s
Segmentation fault
[raiz@localhost slstatus]$
```

`config.h`:
```
#define UPDATE_INTERVAL 1
#define UNKNOWN_STR "n/a"
#define MAXLEN 2048

static const struct arg args[] = {
        { keyboard_indicators, "%s", NULL },
};
```

### CODE REVIEW

**Comment by drkhsh** [comment]
Merged

**Comment by drkhsh** [comment]
@R41z could you please use git send-email or something like that to send me patches? github sucks!

**Comment by R41z** [comment]
Yeah?

**Comment by drkhsh** [comment]
mhm

**Pull request closed without merging**
