### PR TITLE
New features and bugfixes

### PR DESCRIPTION
**Pull request by R41z**
NOTE: that I enabled the stack protector and bugs started showing up (first one here: https://github.com/drkhsh/slstatus/commit/3bcd305d38dd724b7a08391e6b456c5b082645f0), so expect the program to crash on the future because of bugs we did not discover.

### CODE REVIEW

**Comment by drkhsh** [comment]
Looks nice, thanks. I will have a look the next days!

**Comment by drkhsh** [comment]
Could you explain what bugs?

**Comment by R41z** [comment]
Try enabling the stack protector in your current tree and compile the program... (tl;dr: https://github.com/drkhsh/slstatus/pull/36/commits/3bcd305d38dd724b7a08391e6b456c5b082645f0)

**Comment by drkhsh** [comment]
@R41z what bugs did you encounter with the stack protector?

**Comment by stoeckmann** [comment]
The bug @R41z refers to is not always noticeable. It really depends on the way your stack is managed. But the buf[sizeof(buf] = '\0' assignment could hit the stack canary, in which case your program would get killed. I write "could" because it really depends on the stack. If buf is not at the top of it, it won't happen. If your machine has stack alignment, additional (unused) bytes could be between canary and buffer -- it wouldn't happen then again.

This pull request is in conflict now, but the conflicting part is independently fixed now.

**Comment by drkhsh** [comment]
@R41z @stoeckmann I manually added most of the changes from this pr to slstatus. thank you very much for your great work @R41z!

@R41z the both new flags are really stupid... for input i could use wmtool (like mentioned in dwm documentation) and the statusbar without sleep time uses way too much cpu. thus i did not add these two flags.

**Pull request closed without merging**
