### PR TITLE
Add functions for measuring swap

### PR DESCRIPTION
**Pull request by jodizzle**
Implements the following functions:
```c
static char *swap_free(void);
static char *swap_perc(void);
static char *swap_used(void);
static char *swap_total(void);
```
I also updated `config.def.h` and `README.md` to reflect these additions.

The functions are very similar in style and output to the functions for measuring RAM.  The main difference is that not all the swap information in `/proc/meminfo` is right at the top of the file, and so instead of using `fscanf` and skipping a lot of lines, I use `fread` followed by `strstr` and `sscanf`.

If something seems weird about my style or approach here, I'd be happy to discuss it.

### CODE REVIEW

**Comment by drkhsh** [comment]
The changes look very good! I will merge later after some testing.

**Comment by jodizzle** [comment]
Just realized I forgot to cover the case where the user has no swap space allocated.  Currently it leads to a divide-by-zero crash.  My bad!  I'll push a fix soon.

**Comment by drkhsh** [comment]
Thanks! Will push then...

**Comment by jodizzle** [comment]
Alright, I think I addressed the issue.

**Comment by drkhsh** [comment]
@jodizzle Sorry for the delay. Could you implement the functions in the port branch too?

**Comment by jodizzle** [comment]
What do you mean exactly?  If you mean copy the work over to the relevant files in the `port` branch (putting the swap functions in `slstatus.linux.c`, etc.), then yes I could do that, but you could also merge the changes over there yourself after you accept this pull request.  If you mean that you want me to implement the `swap` functions for BSD, then no, I don't think I know how to do that (at least not yet).

Either way, I'm pretty sure I would need to open another pull request in addition to this one.  I don't think I can edit files from two different branches on this one pull request.

**Comment by drkhsh** [comment]
Hmm yeah that would be good, if you want just open another PR for the port branch and implement them only in linux as many others!

**Comment by drkhsh** [comment]
So I will merge this one!

**Comment by drkhsh** [comment]
lol, fucking smartphone xD

**Comment by jodizzle** [comment]
Alright, I'll open another PR soon for changes to the `port` branch.

**Comment by drkhsh** [comment]
Thanks!

**Pull request closed without merging**
